- name: disable mysql default version
  ansible.builtin.shell: yum module disable mysql -y 

- name: coping mysql repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: installing mysql-community-server
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: enable and start mysqld service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: yes

- name: changing default password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1